// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalPark.Data;

#nullable disable

namespace NationalPark.Data.Migrations
{
    [DbContext(typeof(NationalParkDbContext))]
    [Migration("20250527053556_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NationalPark.Data.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("good")
                        .HasColumnName("condition");

                    b.Property<DateTime>("InstalledOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("installedon");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("material");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zoneid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("facility");
                });

            modelBuilder.Entity("NationalPark.Data.Models.PlantSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("bit")
                        .HasColumnName("isprotected");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("latinname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LatinName")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("plantspecies");
                });

            modelBuilder.Entity("NationalPark.Data.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaHa")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("areaha");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("zone");
                });

            modelBuilder.Entity("NationalPark.Data.Models.ZonePlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Density")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("density");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plantid");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zoneid");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("ZoneId", "PlantId")
                        .IsUnique();

                    b.ToTable("zoneplant", t =>
                        {
                            t.HasCheckConstraint("CK_ZonePlant_Density", "[density] IN ('rare', 'medium', 'common')");
                        });
                });

            modelBuilder.Entity("NationalPark.Data.Models.Facility", b =>
                {
                    b.HasOne("NationalPark.Data.Models.Zone", "Zone")
                        .WithMany("Facilities")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("NationalPark.Data.Models.ZonePlant", b =>
                {
                    b.HasOne("NationalPark.Data.Models.PlantSpecies", "PlantSpecies")
                        .WithMany("ZonePlants")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NationalPark.Data.Models.Zone", "Zone")
                        .WithMany("ZonePlants")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantSpecies");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("NationalPark.Data.Models.PlantSpecies", b =>
                {
                    b.Navigation("ZonePlants");
                });

            modelBuilder.Entity("NationalPark.Data.Models.Zone", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("ZonePlants");
                });
#pragma warning restore 612, 618
        }
    }
}
