// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyQuiz.Data;

#nullable disable

namespace MoneyQuiz.Data.Migrations
{
    [DbContext(typeof(MoneyQuizDbContext))]
    [Migration("20250429071334_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoneyQuiz.Data.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.Lifeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerGameSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsedOnQuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerGameSessionId");

                    b.HasIndex("UsedOnQuestionId");

                    b.ToTable("Lifelines");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.PlayerAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("PlayerSessionId");

                    b.ToTable("PlayersAnswers");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.PlayerGameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayersGameSessions");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.Answer", b =>
                {
                    b.HasOne("MoneyQuiz.Data.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.Lifeline", b =>
                {
                    b.HasOne("MoneyQuiz.Data.Models.PlayerGameSession", "PlayerGameSession")
                        .WithMany("Lifelines")
                        .HasForeignKey("PlayerGameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyQuiz.Data.Models.Question", "UserOnQuestion")
                        .WithMany("Lifelines")
                        .HasForeignKey("UsedOnQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerGameSession");

                    b.Navigation("UserOnQuestion");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.PlayerAnswer", b =>
                {
                    b.HasOne("MoneyQuiz.Data.Models.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyQuiz.Data.Models.PlayerGameSession", "PlayerGameSession")
                        .WithMany("PlayerAnswers")
                        .HasForeignKey("PlayerSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("PlayerGameSession");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.PlayerGameSession", b =>
                {
                    b.HasOne("MoneyQuiz.Data.Models.GameSession", "GameSession")
                        .WithMany("PlayersGameSessions")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyQuiz.Data.Models.Player", "Player")
                        .WithMany("PlayersGameSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.GameSession", b =>
                {
                    b.Navigation("PlayersGameSessions");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.Player", b =>
                {
                    b.Navigation("PlayersGameSessions");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.PlayerGameSession", b =>
                {
                    b.Navigation("Lifelines");

                    b.Navigation("PlayerAnswers");
                });

            modelBuilder.Entity("MoneyQuiz.Data.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Lifelines");
                });
#pragma warning restore 612, 618
        }
    }
}
